# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_OperationDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
	def setupUi(self, Dialog):
		Dialog.setObjectName("Dialog")
		Dialog.resize(800, 600)
		sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
		sizePolicy.setHorizontalStretch(0)
		sizePolicy.setVerticalStretch(0)
		sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
		Dialog.setSizePolicy(sizePolicy)
		self.label = QtWidgets.QLabel(Dialog)
		self.label.setGeometry(QtCore.QRect(20, 20, 47, 12))
		self.label.setObjectName("label")
		self.label_2 = QtWidgets.QLabel(Dialog)
		self.label_2.setGeometry(QtCore.QRect(20, 90, 56, 12))
		self.label_2.setObjectName("label_2")
		self.lineEdit = QtWidgets.QLineEdit(Dialog)
		self.lineEdit.setGeometry(QtCore.QRect(20, 40, 131, 19))
		self.lineEdit.setObjectName("lineEdit")
		self.textEdit = QtWidgets.QTextEdit(Dialog)
		self.textEdit.setGeometry(QtCore.QRect(20, 110, 256, 192))
		self.textEdit.setObjectName("textEdit")
		self.pushButton = QtWidgets.QPushButton(Dialog)
		self.pushButton.setGeometry(QtCore.QRect(200, 40, 75, 23))
		self.pushButton.setObjectName("pushButton")
		self.treeWidget = QtWidgets.QTreeWidget(Dialog)
		self.treeWidget.setGeometry(QtCore.QRect(365, 20, 431, 341))
		self.treeWidget.setAutoFillBackground(False)
		self.treeWidget.setColumnCount(2)
		self.treeWidget.setObjectName("treeWidget")
		self.treeWidget.headerItem().setText(0, "1")
		self.treeWidget.headerItem().setText(1, "2")
		self.widget = QtWidgets.QWidget(Dialog)
		self.widget.setGeometry(QtCore.QRect(550, 370, 239, 25))
		self.widget.setObjectName("widget")
		self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
		self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
		self.horizontalLayout.setObjectName("horizontalLayout")
		self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
		self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
		self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
		self.buttonBox.setObjectName("buttonBox")
		self.horizontalLayout.addWidget(self.buttonBox)
		self.buttonBox_2 = QtWidgets.QDialogButtonBox(self.widget)
		self.buttonBox_2.setStandardButtons(QtWidgets.QDialogButtonBox.Apply)
		self.buttonBox_2.setObjectName("buttonBox_2")
		self.horizontalLayout.addWidget(self.buttonBox_2)

		self.retranslateUi(Dialog)
		self.buttonBox.accepted.connect(Dialog.accept)
		self.buttonBox.rejected.connect(Dialog.reject)
		QtCore.QMetaObject.connectSlotsByName(Dialog)
		Dialog.setTabOrder(self.textEdit, self.pushButton)
		Dialog.setTabOrder(self.pushButton, self.lineEdit)
		Dialog.setTabOrder(self.lineEdit, self.treeWidget)

	def retranslateUi(self, Dialog):
		_translate = QtCore.QCoreApplication.translate
		Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
		self.label.setText(_translate("Dialog", "TextLabel"))
		self.label_2.setText(_translate("Dialog", "TextLabel 2"))
		self.pushButton.setText(_translate("Dialog", "PushButton"))
